# Generated by Django 3.1.2 on 2020-10-07 20:26
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('uuid', models.CharField(max_length=50, primary_key=True)),
                ('status', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('task_type', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=50)),
            ],
        ),
    ]
